# Generated by Django 2.1.5 on 2019-03-09 04:53

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('product_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='man', max_length=16)),
                ('age', models.IntegerField()),
                ('nickname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='평점', max_digits=5)),
                ('running_time', models.IntegerField(default=0, help_text='영화 시간, 분을 기준으로')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('director', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_owner',
            field=models.ManyToManyField(to='product_recommendation.BusinessPartner'),
        ),
        migrations.AddField(
            model_name='customer',
            name='associated_bp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_recommendation.BusinessPartner'),
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(to='product_recommendation.Movie'),
        ),
    ]
