# Generated by Django 2.1.3 on 2018-11-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaa', models.CharField(default='비어있음', help_text='여기는 이 필드가 뭔지 주석 쓰는 부분 여기 작성하면 api문서가 알아서 문서화 해줌',
                                         max_length=100)),
                ('bbb', models.CharField(default='비어있음', help_text='여기는 이 필드가 뭔지 주석 쓰는 부분 여기 작성하면 api문서가 알아서 문서화 해줌22',
                                         max_length=100)),
            ],
        ),
    ]
