# Generated by Django 2.1.7 on 2019-04-07 13:07

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('name', models.CharField(help_text="배우 이름, ',' 를 기준으로 분류", max_length=128)),
                ('actor_pk', models.CharField(help_text='영화의 PrimaryKey', max_length=64, primary_key=True, serialize=False)),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActorMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_recommendation.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPartnerMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(help_text='고객의 성별, True 남성, False 여성')),
                ('age', models.IntegerField(help_text='고객의 나이')),
                ('nickname', models.CharField(help_text='업체에서의 ID', max_length=64)),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=None, help_text='고객의 영화에 대한 평점')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_recommendation.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_pk', models.CharField(help_text='영화의 PrimaryKey', max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='영화 제목', max_length=128)),
                ('genre', models.CharField(help_text="영화 장르, ',' 를 기준으로 분류", max_length=128)),
                ('description', models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eget consequat eros, a lacinia turpis. Phasellus faucibus commodo diam', help_text='영화 줄거리', max_length=256, null=True)),
                ('rate', models.FloatField(default=0.0, help_text='영화 평점')),
                ('votes', models.IntegerField(default=0, help_text='퍙점 투표수')),
                ('running_time', models.IntegerField(default=0, help_text='영화 시간, 분을 기준으로')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('director', models.CharField(help_text="감독명, ',' 를 기준으로 분류", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_owner',
            field=models.ManyToManyField(through='movie_recommendation.BusinessPartnerMovie', to='movie_recommendation.BusinessPartner'),
        ),
        migrations.AddField(
            model_name='customermovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_recommendation.Movie'),
        ),
        migrations.AddField(
            model_name='customer',
            name='associated_bp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_recommendation.BusinessPartner'),
        ),
        migrations.AddField(
            model_name='customer',
            name='movie',
            field=models.ManyToManyField(through='movie_recommendation.CustomerMovie', to='movie_recommendation.Movie'),
        ),
        migrations.AddField(
            model_name='businesspartnermovie',
            name='businessPartner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_recommendation.BusinessPartner'),
        ),
        migrations.AddField(
            model_name='businesspartnermovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_recommendation.Movie'),
        ),
        migrations.AddField(
            model_name='actormovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_recommendation.Movie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(through='movie_recommendation.ActorMovie', to='movie_recommendation.Movie'),
        ),
    ]
