# Generated by Django 2.1.5 on 2019-03-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommendation', '0002_auto_20190309_0453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asdf',
        ),
    ]
