# Generated by Django 2.1.7 on 2019-04-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommendation', '0003_auto_20190408_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(help_text="감독명, ',' 를 기준으로 분류", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='genre', help_text="영화 장르, ',' 를 기준으로 분류", max_length=256),
        ),
    ]
