# Generated by Django 2.1.7 on 2019-04-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommendation', '0004_auto_20190408_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(help_text="배우 이름, ',' 를 기준으로 분류", max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='영화 제목', max_length=256),
        ),
    ]
