# Generated by Django 2.1.7 on 2019-08-03 04:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommendation', '0007_auto_20190416_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(help_text='고객의 성별, M 남성, F 여성', max_length=32)),
                ('age', models.IntegerField(help_text='고객의 나이')),
                ('nickname', models.CharField(help_text='업체에서의 ID', max_length=64)),
                ('occupation', models.CharField(help_text='직업', max_length=128, null=True)),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('businessPartner', models.ManyToManyField(to='movie_recommendation.BusinessPartner')),
            ],
        ),
        migrations.CreateModel(
            name='NewMovie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='영화 제목', max_length=256)),
                ('description', models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', help_text='영화 줄거리', max_length=256, null=True)),
                ('rate', models.FloatField(default=0.0, help_text='영화 평점')),
                ('votes', models.IntegerField(default=0, help_text='퍙점 투표수')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('released_date', models.DateTimeField()),
                ('unknown', models.BooleanField(help_text='기타')),
                ('action', models.BooleanField(help_text='액션')),
                ('adventure', models.BooleanField(help_text='모험')),
                ('animation', models.BooleanField(help_text='애니메이션')),
                ('children', models.BooleanField(help_text='유아')),
                ('comedy', models.BooleanField(help_text='코미디')),
                ('crime', models.BooleanField(help_text='범죄')),
                ('documentary', models.BooleanField(help_text='다큐멘터리')),
                ('drama', models.BooleanField(help_text='드라마')),
                ('fantasy', models.BooleanField(help_text='판타지')),
                ('film_noir', models.BooleanField(help_text='누아르')),
                ('horror', models.BooleanField(help_text='공포')),
                ('musical', models.BooleanField(help_text='뮤지컬')),
                ('mystery', models.BooleanField(help_text='미스터리')),
                ('romance', models.BooleanField(help_text='로맨스')),
                ('sci_fi', models.BooleanField(help_text='과학')),
                ('thriller', models.BooleanField(help_text='스릴러')),
                ('war', models.BooleanField(help_text='전쟁')),
                ('western', models.BooleanField(help_text='서부')),
                ('businessPartner', models.ManyToManyField(to='movie_recommendation.BusinessPartner')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=None, help_text='고객의 영화에 대한 평점')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_recommendation.NewCustomer')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_recommendation.NewMovie')),
            ],
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='movie',
            field=models.ManyToManyField(through='movie_recommendation.Ratings', to='movie_recommendation.NewMovie'),
        ),
    ]
