# Generated by Django 2.1.7 on 2019-08-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommendation', '0008_auto_20190803_1359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('nickname', 'associated_bp')},
        ),
    ]
