# Generated by Django 2.1.7 on 2019-08-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommendation', '0009_auto_20190803_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(db_index=True, default='genre', help_text="영화 장르, ',' 를 기준으로 분류", max_length=256),
        ),
    ]
