# Generated by Django 2.1.7 on 2019-08-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommendation', '0012_auto_20190808_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmovie',
            name='released_date',
            field=models.DateField(),
        ),
    ]
