# Generated by Django 2.1.7 on 2019-08-09 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommendation', '0013_auto_20190809_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmovie',
            name='released_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
